### ISSUE TITLE
Error thrown when no media is present

### ISSUE THREAD

**Issue by ThomasMcFarlane** [sourcetoad/node-social-feed-api#1]
API.js#35 throws an error if there is no media on a Facebook post due to the attachments object being null.
This needs to be checked before accessing data[i].attachments.data.

Changing this to the following will fix it (albeit in a crude manner):
`media: (data[i].attachments && data[i].attachments.data[0]) ? {`

**Comment by kaplanmaxe** [comment]
Fix for this is now in 1.1.3. Thanks!
